name: Deploy hugging face space
description: Creates and deploys a gradio or static hugging face space. If the space already exists, it will be updated.
inputs:
  hf_token:
    description: "Your Hugging Face access token."
    required: true
  gh_token:
    description: "Your github token, required for commenting on PRs"
  user_name:
    description: "The user name to create a space for."
    required: true
  space_name:
    description: "The name of the space to create."
    required: true
  space_type:
    description: "The type of space to create. Can be 'gradio' or 'static'."
    default: "gradio"
  path:
    description: "The path to the directory containing the app or the name of the artifact."
    required: true
  comment:
    description: "Whether or not to comment on the PR. true | false"
    default: true
  is_artifact:
    description: "The path to the directory containing the app."
    default: false

runs:
  using: "node16"
  main: "dist/index.js"
