name: comment_pr
description: Creates and deploys a gradio or static hugging face space. If the space already exists, it will be updated.
inputs:
  token:
    description: "Your Hugging Face access token."
    required: true
  

runs:
  using: "node16"
  main: "dist/index.js"
