name: comment_pr
description: Creates and deploys a gradio or static hugging face space. If the space already exists, it will be updated.
inputs:
  gh_token:
    description: "Your github token."
    required: true
  tag:
    description: "Fixed id for your comment."
    required: true
  message:
    description: "Message to comment."
    required: true
  additional_text:
    description: "Additional text to comment."
    required: false
  pr_number:
    description: "Pull request number."
    required: true

runs:
  using: "node16"
  main: "dist/index.js"
