name: Comment on pull request without race conditions

on:
  workflow_call:
    inputs:
      pr_number:
        required: true
        type: string
      message:
        required: true
        type: string
      tag:
        required: false
        type: string
        default: "previews"
    secrets:
      gh_token:
        required: true

concurrency:
  group: ${{ github.event.inputs.pr_number }}

jobs:
  comment:
    runs-on: ubuntu-latest
    steps:
      - run: echo token = ${{ secrets.gh_token }}
      - run: echo pr_number = ${{ inputs.pr_number }}
      - run: echo message = ${{ inputs.message }}
      # - name: test action
      #   uses: './.github/actions/comment_pr'
      #   with:
      #     token: ${{ secrets.GITHUB_TOKEN }}
      #     id: some_id
      #     message: "Hello, the branch name is ${{ inputs.pr_number }}. Number two."
      # - uses: "gradio-app/github/actions/comment_pr@main"
      #   with:
      #     github_token: ${{ inputs.token }}
      #     pr_number: ${{ inputs.pr_number }}
      #     message: ${{ inputs.message }}
      #     tag: ${{ inputs.tag }}
