name: Comment on pull request without race conditions

on:
  workflow_call:
    inputs:
      pr_number:
        required: true
        type: string
      message:
        required: true
        type: string
      tag:
        required: false
        type: string
        default: "previews"
    secrets:
      gh_token:
        required: true

concurrency:
  group: 1

jobs:
  comment:
    runs-on: ubuntu-latest
    steps:
      - run: echo token = ${{ secrets.gh_token }}
      - run: echo pr_number = ${{ inputs.pr_number }}
      - run: echo message = ${{ inputs.message }}
      - run: echo tag = ${{ inputs.tag }}
      - name: test action
        uses: "./.github/actions/comment_pr"
        with:
          token: ${{ secrets.gh_token }}
          tag: ${{ inputs.tag }}
          pr_number: ${{ inputs.pr_number}}
          message: ${{ inputs.message }}
      # - uses: "gradio-app/github/actions/comment_pr@main"
      #   with:
      #     github_token: ${{ inputs.token }}
      #     pr_number: ${{ inputs.pr_number }}
      #     message: ${{ inputs.message }}
      #     tag: ${{ inputs.tag }}
