name: trigger

on:
  pull_request:
    types: [opened, synchronize, reopened, edited, labeled, unlabeled]
    branches:
      - main
  issue_comment:
    types: [edited]

jobs:
  version:
    permissions: write-all
    name: trigger
    runs-on: ubuntu-22.04
    steps:
      - run: echo "Triggering run"