name: ui

on:
  push:
    branches: [ main ]
  pull_request:

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - name: checkout
        uses: actions/checkout@v3
      - name: Extract branch name
        shell: bash
        run: echo "branch=${GITHUB_HEAD_REF:-${GITHUB_REF#refs/heads/}}" >> $GITHUB_OUTPUT
        id: extract_branch
      - name: echo branch name
        run: echo ${{ steps.extract_branch.outputs.branch }}
      - name: test action
        uses: './.github/actions/comment_pr'
        with:
          token: ${{ secrets.GITHUB_TOKEN }}

