name: ui

on:
  push:
    branches: [ main ]
  pull_request:

jobs:
  build:
    permissions: write-all
    runs-on: ubuntu-latest
    outputs:
      branch_name: ${{ steps.extract_branch.outputs.branch }}
    steps:
      - name: checkout
        uses: actions/checkout@v3
      - name: Extract branch name
        shell: bash
        run: echo "branch=${GITHUB_HEAD_REF:-${GITHUB_REF#refs/heads/}}" >> $GITHUB_OUTPUT
        id: extract_branch
      - name: echo branch name
        run: echo ${{ steps.extract_branch.outputs.branch }}
  deploy:
    uses: "./.github/workflows/deploy-website.yml"
    needs: build
    secrets:
      gh_token: ${{ secrets.GITHUB_TOKEN }}
      vercel_token: ${{ secrets.VERCEL_TOKEN }}
    with:
      branch_name: ${{ needs.build.outputs.branch_name }}
      pr_number: ${{ github.event.number }}
